---
- name: Manage storage.conf
  when: podman_storage_conf | length > 0
  block:
    - name: Ensure storage.conf parent dir exists
      file:
        path: "{{ __podman_storage_conf_file | dirname }}"
        state: directory
        owner: "{{ podman_run_as_user }}"
        group: "{{ podman_run_as_group if
          podman_run_as_group is not none else omit }}"
        mode: "0755"

    - name: Convert storage config to TOML
      podman_to_toml:
        data: "{{ podman_storage_conf }}"
        use_new_formatter: "{{ podman_use_new_toml_formatter }}"
      register: __podman_to_toml

    - name: Update storage config file
      copy:
        content: "{{ header + __podman_to_toml.toml }}"
        dest: "{{ __podman_storage_conf_file }}"
        owner: "{{ podman_run_as_user }}"
        group: "{{ podman_run_as_group if
          podman_run_as_group is not none else omit }}"
        mode: "0644"
      vars:
        header: "{{ lookup('template', 'get_ansible_managed.j2') }}"
      register: __podman_storage_config_register
