---
# Input:
# * __podman_quadlet_file - path to quadlet file to parse
# Output:
# * __podman_quadlet_parsed - dict
- name: Slurp quadlet file
  slurp:
    path: "{{ __podman_quadlet_file }}"
  register: __podman_quadlet_raw
  no_log: true

- name: Parse quadlet file
  set_fact:
    __podman_quadlet_parsed: "{{ __podman_quadlet_raw.content | b64decode | podman_from_ini }}"
  when:
    - __podman_service_name is not none
    - __podman_service_name | length > 0
  no_log: true

- name: Parse quadlet yaml file
  set_fact:
    __podman_quadlet_parsed: "{{ __podman_quadlet_raw.content | b64decode |
      from_yaml_all | list }}"
  when:
    - __podman_service_name is none or __podman_service_name | length == 0
    - __podman_quadlet_file.endswith(".yml") or
      __podman_quadlet_file.endswith(".yaml")
  no_log: true

- name: Reset raw variable
  set_fact:
    __podman_quadlet_raw: null
